---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: inventory-extension-odg

namespace: default

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
